server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: document
          uri: http://localhost:8042
          predicates:
            - Path=/documents/**, 
        - id: thumbnail
          uri: http://localhost:8043
          predicates:
            - Path=/thumbnail/**, 
        - id: receiving
          uri: http://localhost:8082
          predicates:
            - Path=/receivings/**, 
        - id: consultation
          uri: http://localhost:8083
          predicates:
            - Path=/consultations/**, 
        - id: insurance
          uri: http://localhost:8084
          predicates:
            - Path=/insurances/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: receiving
          uri: http://receiving:8080
          predicates:
            - Path=/receivings/**, 
        - id: consultation
          uri: http://consultation:8080
          predicates:
            - Path=/consultations/**, 
        - id: insurance
          uri: http://insurance:8080
          predicates:
            - Path=/insurances/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
